namespace PoeWikiData.Models.Enums
{
    public enum DropSources
    {
        None,
        AbyssalBoss,
        AbyssalTroveStygianSpire,
        AtlasMapBoss,
        TheBeachhead,
        BlightedMap,
        BlightRavagedMap,
        BreachBreachstone,
        CorruptionAltar,
        CurioDisplay,
        DeliriumBoss,
        AzuriteMineBoss,
        DomainOfTimelessConflict,
        ExpeditionLogbookBoss,
        ExpeditionZone,
        FlawlessBreachstone,
        HarbingerCraft,
        HeistBoss,
        TempleOfAtzoatlRoom,
        VaalOmnitect,
        Labyrinth,
        LegionGeneral,
        MastermindsLair,
        RitualAltar,
        Sanctum,
        SanctumWithRelic,
        Simulacrum,
        SmugglersCache,
        SyndicateSafehouse,
        Tier17MapBoss,
        Trialmaster,
        UltimatumTrial,
        Warband
    }
}
