namespace PoeWikiData.Models.Enums
{
    //public enum ItemClasses
    //{
    //    None,
    //    AbyssJewel,
    //    Amulet,
    //    Belt,
    //    BodyArmour,
    //    Boots,
    //    Bow,
    //    Claw,
    //    Contract,
    //    Dagger,
    //    FishingRod,
    //    Gloves,
    //    Helmet,
    //    HybridFlask,
    //    ItemPiece,
    //    Jewel,
    //    LifeFlask,
    //    ManaFlask,
    //    Map,
    //    OneHandedAxe,
    //    OneHandedMace,
    //    OneHandedSword,
    //    Quiver,
    //    Relic,
    //    Ring,
    //    RuneDagger,
    //    Sceptre,
    //    Shield,
    //    Staff,
    //    ThrustingOneHandedSword,
    //    TwoHandedAxe,
    //    TwoHandedMace,
    //    TwoHandedSword,
    //    UtilityFlask,
    //    Wand,
    //    Warstaff
    //}
}
